language: ruby
addons:
  firefox: "18.0"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
rvm:
  - 2.0.0
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
notifications:
  email: false
  irc:
    on_success: always
    on_failure: always
    channels:
      - "card.freenode.net#dukedevelopers"
