language: ruby
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.29.0.jar"
  - "java -jar selenium-server-standalone-2.29.0.jar > /dev/null 2>&1 &"
  - "sleep 30"
rvm:
  - 2.0.0
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "card.freenode.net#dukedevelopers"
