language: ruby
bundler_args: --without development
addons:
  firefox: "18.0"
services:
  - redis-server
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
rvm:
  - 2.0.0
script: 
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
notifications:
  email:
    - leonard@chpir.org
branches:
  only:
    -master
    -develop