language: ruby
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
rvm:
  - 2.0.0
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
  - bundle exec rspec spec
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "card.freenode.net#dukedevelopers"
