language: ruby
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
rvm:
  - 2.0.0
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "card.freenode.net#dukedevelopers"
