# MINIMUM ANDROID VERSION ALLOWED
minimum_android_version_code: 5

question_types: ['SELECT_ONE', 'SELECT_MULTIPLE', 'SELECT_ONE_WRITE_OTHER', 'SELECT_MULTIPLE_WRITE_OTHER', 'FREE_RESPONSE', 'SLIDER', 'DATE', 'RATING', 'TIME', 'LIST_OF_TEXT_BOXES', 'INTEGER', 'EMAIL_ADDRESS', 'DECIMAL_NUMBER', 'INSTRUCTIONS', 'MONTH_AND_YEAR', 'YEAR', 'PHONE_NUMBER', 'ADDRESS', 'REAR_PICTURE', 'FRONT_PICTURE', 'SELECT_ONE_IMAGE', 'SELECT_MULTIPLE_IMAGE', 'LIST_OF_INTEGER_BOXES', 'LABELED_SLIDER', 'GEO_LOCATION']
critical_type_questions: ['SELECT_ONE', 'SELECT_MULTIPLE']
question_with_options: ['SELECT_ONE', 'SELECT_MULTIPLE', 'SELECT_ONE_WRITE_OTHER', 'SELECT_MULTIPLE_WRITE_OTHER', 'LIST_OF_TEXT_BOXES', 'LIST_OF_INTEGER_BOXES', 'LABELED_SLIDER']
question_with_images: ['SELECT_ONE_IMAGE', 'SELECT_MULTIPLE_IMAGE']
question_with_other: ['SELECT_ONE_WRITE_OTHER', 'SELECT_MULTIPLE_WRITE_OTHER']
question_with_select_multiple: ['SELECT_MULTIPLE', 'SELECT_MULTIPLE_WRITE_OTHER', 'SELECT_MULTIPLE_IMAGE']
question_with_multiple_skips: ['SELECT_ONE']
question_with_skips: ['SELECT_ONE']
question_without_options: ['FREE_RESPONSE', 'SLIDER', 'DATE', 'RATING', 'TIME', 'INTEGER', 'EMAIL_ADDRESS', 'DECIMAL_NUMBER', 'INSTRUCTIONS', 'MONTH_AND_YEAR', 'YEAR', 'PHONE_NUMBER', 'ADDRESS', 'REAR_PICTURE', 'FRONT_PICTURE']
scoreable_question_types: ['SELECT_ONE', 'SELECT_MULTIPLE', 'SELECT_ONE_WRITE_OTHER', 'SELECT_MULTIPLE_WRITE_OTHER', 'INTEGER', 'DECIMAL_NUMBER', 'SLIDER', 'LABELED_SLIDER', 'RATING', 'LIST_OF_TEXT_BOXES', 'FREE_RESPONSE']
list_question_types: ['LIST_OF_INTEGER_BOXES', 'LIST_OF_TEXT_BOXES']

rule_types:
  instrument_survey_limit_rule:
    constant_name: 'INSTRUMENT_SURVEY_LIMIT_RULE'
    pretty_name: 'Instrument Survey Limit Rule'
    params: ['max_surveys']
    description: 'Limit the number of surveys that can be created for an instrument per device.'
  instrument_timing_rule:
    constant_name: 'INSTRUMENT_TIMING_RULE'
    pretty_name: 'Instrument Timing Rule'
    params: ['start_time', 'end_time']
    description: 'Only make this instrument available during certain times of the day.'
  instrument_survey_limit_per_minute_rule:
    constant_name: 'INSTRUMENT_SURVEY_LIMIT_PER_MINUTE_RULE'
    pretty_name: 'Instrument Survey Limit Per Minute Rule'
    params: ['num_surveys', 'minute_interval']
    description: 'Limit the number of surveys that can be completed per time interval (specified in minutes).'
  instrument_launch_rule:
    constant_name: 'INSTRUMENT_LAUNCH_RULE'
    pretty_name: 'Instrument Launch Rule'
    params: []
    description: 'Setting this rule will make it so that a survey cannot be generated for an instrument from the app.  A survey must be launched from another app.'
  participant_type_rule:
    constant_name: 'PARTICIPANT_TYPE_RULE'
    pretty_name: 'Participant Type Rule'
    params: ['Child', 'Caregiver', 'Center', 'Neighbour']
    description: 'Limit an instrument such that it can only be created for a certain type of participant.'
  participant_age_rule:
    constant_name: 'PARTICIPANT_AGE_RULE'
    pretty_name: 'Participant Age Rule'
    params: ['start_age', 'end_age']
    description: 'Limit an instrument so a survey can only be created if the age of the participant falls within the range'

# List delimiter for options
list_delimiter: ','

# Delimiter for items in option dictionary
dictionary_delimiter: ';'

# ISO 639-1 codes of supported languages
languages: [
             ['English', 'en'],
             ['Amharic', 'am'],
             ['Arabic', 'ar'],
             ['Khmer', 'km'],
             ['Spanish', 'es'],
             ['Swahili', 'sw'],
             ['Telugu', 'te'],
             ['Chinese', 'zh']
          ]

# Special Responses
special_responses: ['SKIP', 'NA', 'RF', 'DK']
any_default_non_empty_response: 'ANY RESPONSE'
skipped_question_special_response: 'SKIP'

right_align_languages: ['ar']

exception_notifications:
  email_prefix: '[RailsSurvey] '
  sender: 'noreply@chpir.org'
  recipients: ['leonard@chpir.org']

danger_zone_days: 3

metric_keys: ['device_uuid', 'Participant ID', 'Center ID']

roster_types: ['STAFF','CHILD']

display_types: ['SINGLE', 'MULTIPLE', 'TABULAR']
