question_types: ['SELECT_ONE', 'SELECT_MULTIPLE', 'SELECT_ONE_WRITE_OTHER',
        'SELECT_MULTIPLE_WRITE_OTHER', 'FREE_RESPONSE', 'SLIDER', 'FRONT_PICTURE',
        'REAR_PICTURE']
question_with_options: ['SELECT_ONE', 'SELECT_MULTIPLE', 'SELECT_ONE_WRITE_OTHER',
        'SELECT_MULTIPLE_WRITE_OTHER']
languages: ['english', 'khmer', 'arabic', 'telugu', 'swahili', 'amharic']
right_align_languages: ['arabic']
