# MINIMUM ANDROID VERSION ALLOWED
minimum_android_version_code: 1

#PENDING QUESTION TYPES: FRONT_PIcTURE, REAR_PICTURE
question_types: ['SELECT_ONE', 'SELECT_MULTIPLE', 'SELECT_ONE_WRITE_OTHER',
        'SELECT_MULTIPLE_WRITE_OTHER', 'FREE_RESPONSE', 'SLIDER', 'DATE', 
        'RATING', 'TIME', 'LIST_OF_TEXT_BOXES', 'INTEGER']
question_with_options: ['SELECT_ONE', 'SELECT_MULTIPLE', 'SELECT_ONE_WRITE_OTHER',
        'SELECT_MULTIPLE_WRITE_OTHER', 'LIST_OF_TEXT_BOXES']

# ISO 639-1 codes of supported languages
languages: ['en', 'es', 'km', 'ar', 'te', 'sw', 'am']
right_align_languages: ['ar']

exception_notifications:
  email_prefix: '[RailsSurvey] '
  sender: 'noreply@chpir.org'
  recipients: ['michael@chpir.org']
