# MINIMUM ANDROID VERSION ALLOWED
minimum_android_version_code: 5

question_types: 
        ['SELECT_ONE', 'SELECT_MULTIPLE', 'SELECT_ONE_WRITE_OTHER',
        'SELECT_MULTIPLE_WRITE_OTHER', 'FREE_RESPONSE', 'SLIDER', 'DATE', 
        'RATING', 'TIME', 'LIST_OF_TEXT_BOXES', 'INTEGER', 'EMAIL_ADDRESS',
        'DECIMAL_NUMBER', 'INSTRUCTIONS', 'MONTH_AND_YEAR', 'YEAR', 
        'PHONE_NUMBER', 'ADDRESS', 'REAR_PICTURE', 'FRONT_PICTURE',
        'SELECT_ONE_IMAGE', 'SELECT_MULTIPLE_IMAGE']

question_with_options: ['SELECT_ONE', 'SELECT_MULTIPLE', 'SELECT_ONE_WRITE_OTHER', 'SELECT_MULTIPLE_WRITE_OTHER', 'LIST_OF_TEXT_BOXES']
question_with_images: ['SELECT_ONE_IMAGE', 'SELECT_MULTIPLE_IMAGE']
question_with_other: ['SELECT_ONE_WRITE_OTHER', 'SELECT_MULTIPLE_WRITE_OTHER']
question_with_select_multiple: ['SELECT_MULTIPLE', 'SELECT_MULTIPLE_WRITE_OTHER', 'SELECT_MULTIPLE_IMAGE']
question_with_multiple_skips: ['SELECT_ONE']

rule_types: 
  instrument_survey_limit_rule:
    constant_name: 'INSTRUMENT_SURVEY_LIMIT_RULE'
    pretty_name: 'Instrument Survey Limit Rule'
    params: ['max_surveys']
    description: 'Limit the number of surveys that can be created for an instrument per device.'
  instrument_timing_rule:
    constant_name: 'INSTRUMENT_TIMING_RULE'
    pretty_name: 'Instrument Timing Rule'
    params: ['start_time', 'end_time']
    description: 'Only make this instrument available during certain times of the day.'
 
# List delimiter for options
list_delimiter: ','

# Delimiter for items in option dictionary
dictionary_delimiter: ';'

# ISO 639-1 codes of supported languages
languages: [
             ['English', 'en'],
             ['Amharic', 'am'],
             ['Arabic', 'ar'],
             ['Khmer', 'km'],
             ['Spanish', 'es'],
             ['Swahili', 'sw'],
             ['Telugu', 'te']
          ]

# Special Responses
special_responses: ['SKIP', 'NA', 'RF', 'DK']

right_align_languages: ['ar']

exception_notifications:
  email_prefix: '[RailsSurvey] '
  sender: 'noreply@chpir.org'
  recipients: ['michael@chpir.org', 'leonard@chpir.org']

questions_per_page: 15
pages_to_show: 15
