:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log
:queues:
  - [default, 1]
  - [status, 1]
  - [export, 1]
  - [cache, 1]
  - [percentage, 1]
  - [questions_reorder, 2]
production:
  :concurrency: 2
  